version: 2
updates:
  - package-ecosystem: "github-actions"
    assignees:
      - "dependabot[bot]"
    commit-message:
      prefix: "deps(root)"
      include: scope
    directory: /
    labels:
      - "dependencies"
      - "automerge"
    reviewers:
      - "valeriobelli"
    schedule:
      interval: "weekly"
