name: "Reusable CD workflow"

on:
  workflow_call:
    inputs:
      package_path:
        required: true
        type: string
        description: "The glob that identity the package for which the CD pipeline should run."

jobs:
  CD:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 18.x

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - name: Setup
        run: yarn install

      - name: Build bundle
        id: build_bundle
        run: yarn turbo run build:bundle --filter="./${{ inputs.package_path }}/**"

      - name: Build tyings
        id: build_typings
        run: yarn turbo run build:typings --filter="./${{ inputs.package_path }}/**"

      - name: Publish
        if: ${{ (steps.build_bundle.outcome == 'success') && (steps.build_typings.outcome == 'success') }}
        run: |
          yarn config set npmAuthToken $NPM_SECRET_KEY
          cd ${{ inputs.package_path }}
          yarn npm publish
        env:
          NPM_SECRET_KEY: ${{ secrets.NPM_SECRET_KEY }}
