name: "Reusable Changesets workflow"

on:
  workflow_call:
    inputs:
      package_name:
        required: true
        type: string
        description: "The package's name for which the Changesets workflow should run."

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: yarn

      - name: Install Dependencies
        run: yarn

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          commit: "feat(${{ inputs.package_name }}): update changelog and semver\n\nrefs #0"
          cwd: ./packages/${{ inputs.package_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
