name: "core/CD"

on:
  push:
    branches:
      - main
    paths:
      - packages/core/**

jobs:
  core:
    uses: "./.github/workflows/_cd.yml"
    with:
      package_name: core
    secrets:
      npm_secret_key: "${{ secrets.NPM_SECRET_KEY }}"
