name: "core/CI"

on:
  push:
    branches:
      - main
    paths:
      - "packages/core/**"
  pull_request:
    branches:
      - main
    paths:
      - "packages/core/**"

jobs:
  core:
    uses: "./.github/workflows/_ci.yml"
    with:
      package_name: core
