name: "CI workflow for @langua/core"

on:
  push:
    branches:
      - main
    paths:
      - "packages/core/**"
  pull_request:
    branches:
      - main
    paths:
      - "packages/core/**"

jobs:
  ci:
    uses: "./.github/workflows/_ci.yml"
    with:
      package_path: "packages/core"
