name: CI

on:
  push:
    branches:
      - main
    paths:
      - "packages/core/**"
  pull_request:
    branches:
      - main
    paths:
      - "packages/core/**"

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 14.x
          - 16.x
          - 18.x

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - name: Setup
        run: yarn install

  build:
    runs-on: ubuntu-latest
    needs: ["setup"]
    strategy:
      matrix:
        node-version:
          - 14.x
          - 16.x
          - 18.x

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - name: Setup
        run: yarn install

      - name: Execute
        run: yarn turbo run build:bundle --filter="./packages/core/**"

  build-typings:
    runs-on: ubuntu-latest
    needs: ["setup"]
    strategy:
      matrix:
        node-version:
          - 14.x
          - 16.x
          - 18.x

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - name: Setup
        run: yarn install

      - name: Execute
        run: yarn turbo run build:typings --filter="./packages/core/**"

  lint:
    runs-on: ubuntu-latest
    needs: ["setup"]
    strategy:
      matrix:
        node-version:
          - 14.x
          - 16.x
          - 18.x

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - name: Setup
        run: yarn install

      - name: Execute
        run: yarn turbo run lint --filter="./packages/core/**"

  typecheck:
    runs-on: ubuntu-latest
    needs: ["setup"]
    strategy:
      matrix:
        node-version:
          - 14.x
          - 16.x
          - 18.x

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - name: Setup
        run: yarn install

      - name: Execute
        run: yarn turbo run typecheck --filter="./packages/core/**"

  tests:
    runs-on: ubuntu-latest
    needs: ["setup"]
    strategy:
      matrix:
        node-version:
          - 14.x
          - 16.x
          - 18.x

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - name: Setup
        run: yarn install

      - name: Execute
        run: yarn turbo run test --filter="./packages/core/**" -- --watch=false
