name: CI

on:
  push:
    branches:
      - main
    paths:
      - "packages/core/**"
  pull_request:
    branches:
      - main
    paths:
      - "packages/core/**"

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 14.x
          - 16.x
          - 18.x

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Setup
        run: yarn install

  build:
    runs-on: ubuntu-latest
    needs: ["setup"]
    strategy:
      matrix:
        node-version:
          - 14.x
          - 16.x
          - 18.x

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Setup
        run: yarn install

      - name: Execute
        run: "yarn nx core:build"

  lint:
    runs-on: ubuntu-latest
    needs: ["setup"]
    strategy:
      matrix:
        node-version:
          - 14.x
          - 16.x
          - 18.x

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Setup
        run: yarn install

      - name: Execute
        run: "yarn nx core:lint"

  typecheck:
    runs-on: ubuntu-latest
    needs: ["setup"]
    strategy:
      matrix:
        node-version:
          - 14.x
          - 16.x
          - 18.x

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Setup
        run: yarn install

      - name: Execute
        run: "yarn nx core:typecheck"

  tests:
    runs-on: ubuntu-latest
    needs: ["setup"]
    strategy:
      matrix:
        node-version:
          - 14.x
          - 16.x
          - 18.x

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Setup
        run: yarn install

      - name: Execute
        run: "yarn nx core:test"
